#!/usr/bin/perl

use warnings;
use strict;
use FindBin;
use lib "$FindBin::Bin";
use RSSBot;

my $config = "";
my @channels;

sub usage {
    use Pod::Usage;
    pod2usage(2);
}

sub parse_cfg {
    usage if not defined $ARGV[0];
    if (not -e $ARGV[0]) {
        print STDERR "File $ARGV[0] does not exist!\n";
        usage;
    }
    use YAML;
    $config = YAML::LoadFile($ARGV[0]);
}

sub allchannels {
    my @out;
    foreach my $f (@{$config->{feeds}}) {
        foreach my $c (@{$f->{channels}}) {
            push @out, $c;
        }
    }
    use List::MoreUtils qw(uniq);
    return uniq(@out);
}


sub sigHUP_handler {
    print "got SIGHUP, reloading configuration\n";
    parse_cfg;
    @channels = allchannels;
}
my $sigset = POSIX::SigSet->new();
my $action = POSIX::SigAction->new('sigHUP_handler', $sigset, &POSIX::SA_NODEFER);
POSIX::sigaction(&POSIX::SIGHUP, $action);

parse_cfg;
@channels = allchannels;

my $RSSBot = RSSBot->new(
        server => $config->{ircserver},
        # log into all the configured channels
        channels => join (",", @channels),
        nick => "rssbot",
        config => \$config,
        flood => 0,
)->run();

__END__
=head1 NAME

rss-bot - IRC Bot, processes RSS feeds and sends notification to a list of channels

=head1 SYNOPSIS

usage: rss-bot config_file

=cut
# vim: set sw=4;
